//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-VJNST16\\VVLONG;Initial Catalog=qlSinhVien;Integrated Security" +
            "=True")]
        public string qlSinhVienConnectionString {
            get {
                return ((string)(this["qlSinhVienConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-VJNST16\\VVLONG;Initial Catalog=QuanLyThuVien;Integrated Secur" +
            "ity=True")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATNGUYEN\\SQLEXPRESS;Initial Catalog=QuanLyThuVien;Integrated Securit" +
            "y=True")]
>>>>>>> c2183447f5afc2a76cabb5504ea5a8cee0c409d9
        public string QuanLyThuVienConnectionString {
            get {
                return ((string)(this["QuanLyThuVienConnectionString"]));
            }
        }
    }
}
